#!/usr/bin/env bash
set -o allexport -o errexit -o nounset -o pipefail
# https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin

# ====================== TODO =======================

# There is no regex support currently for the REST API, look out if there are changes or
# maybe the GraphQL API gets the ability to search code. Currently only ISSUE, REPOSITORY,
# USER and DISCUSSION are supported.

# Check supported search types in the GraphQL API: gh api graphql --raw-field query=$'{
# __type(name: "SearchType") { enumValues { name } }}' \
# --jq '[.data.__type.enumValues[].name] | join(", ")'

# TODO: add tests
# TODO: experiment with 'parallel' to speed things up

# ====================== set variables =======================

debug_mode=false
open_in_editor=false
open_in_pager=false
fzf_prompt="❮❯ Code: "
FZF_API_KEY="$(head -c 32 /dev/urandom | base64)"
BAT_THEME=${BAT_THEME:-Monokai Extended}
# bash is needed to use exported functions when the default shellis not bash
SHELL=bash
# A cached version will be used before a new one is pulled.
gh_default_cache_time="1h"
gh_default_limit=30
gh_user_limit=${gh_user_limit:-$gh_default_limit}
gh_accept_json="Accept: application/vnd.github+json"
gh_accept_raw="Accept: application/vnd.github.raw"
gh_accept_text_match="Accept: application/vnd.github.text-match+json"
gh_rest_api_version="X-GitHub-Api-Version:2022-11-28"
# see https://github.com/junegunn/fzf/blob/master/CHANGELOG.md 'preview-border' option
min_fzf_version="0.43.0"
# TODO: bump version when fixed https://github.com/cli/cli/issues/7674
min_gh_version="2.31.0"

# define colors
COLOR_RESET='\033[0m'
RED_NORMAL='\033[0;31m'
GREEN_NORMAL='\033[0;32m'
YELLOW_NORMAL='\033[0;33m'
MAGENTA_NORMAL="\033[0;35m"
MAGENTA_BOLD="\033[1;35m"
CYAN_NORMAL="\033[0;36m"
CYAN_BOLD="\033[1;36m"
WHITE_NORMAL='\033[0;97m'
WHITE_BOLD='\033[1;97m'
DARK_GRAY='\033[0;90m'

# =========================== basics ============================

cleanup() {
	$debug_mode && printf "%bDebug mode was ON, the following files weren't deleted.%b\n" "$YELLOW_NORMAL" "$COLOR_RESET"
	rm -rf "$scratch_directory" 2>/dev/null
	if ! $debug_mode; then
		rm -rf "$debug_directory" 2>/dev/null
	else
		find "${debug_directory}/"* 2>/dev/null | while read -r matching_file; do
			if [[ ! -s $matching_file ]]; then
				rm -f "$matching_file"
			else
				printf "\t%s\n" "$matching_file"
			fi
		done
	fi
}

die() {
	echo ERROR: "$*" >&2
	exit 1
}

trap cleanup EXIT SIGHUP SIGINT

# Creating temporary files. The current setup works but is very verbose. An attempt to use
# associative arrays with 'declare -A' was unsuccessful as I couldn't access the associated
# filename in child processes.

date_prefix=$(date -u +%Y-%m-%dT%H-%M-%S)
# Default directory for trivial files
scratch_directory=$(mktemp -dt "$date_prefix.gh_find_code") || die "Can't create directory."
store_input_list="${scratch_directory}/input_list"
store_tee_append="${scratch_directory}/tee_append"
store_fzf_port="${scratch_directory}/fzf_port"
store_file_contents="${scratch_directory}/file_content"
store_skip_count="${scratch_directory}/skip_count"

# Debug directory
debug_directory=$(mktemp -dt "$date_prefix.gh_find_code.debug") || die "Can't create debug directory."
store_bat_debug="${debug_directory}/bat_debug"
store_grep_extended_debug="${debug_directory}/grep_extended_debug"
store_gh_search_debug="${debug_directory}/gh_search_debug"
store_gh_content_debug="${debug_directory}/gh_content_debug"

# This function validates the version of a tool.
check_version() {
	local tool=$1 threshold=$2 on_error=${3:-die}
	local user_version
	declare -a ver_parts threshold_parts
	user_version=$($tool --version 2>&1 | grep -Eo '[0-9]+(\.[0-9]+)*' | sed q)

	IFS='.' read -ra ver_parts <<<"$user_version"
	IFS='.' read -ra threshold_parts <<<"$threshold"

	for i in "${!ver_parts[@]}"; do
		if (("${ver_parts[i]}" < "${threshold_parts[i]}")); then
			$on_error "Your '$tool' version '$user_version' is insufficient. The minimum required version is '$threshold'."
		fi
	done
}

# IMPORTANT: Keep it in sync with the readme.md
print_help_text() {
	local help_text
	help_text=$(
		cat <<EOF
GitHub code searching with 'fzf'

${WHITE_BOLD}Usage${COLOR_RESET}
  gh find-code [Flags] [Search query]

${WHITE_BOLD}Flags${COLOR_RESET}
  ${GREEN_NORMAL}-d${COLOR_RESET}  debug mode, primarily used for identifying and resolving bugs
  ${GREEN_NORMAL}-l${COLOR_RESET}  limit the number of listed results (default ${gh_default_limit}, max 100)
  ${GREEN_NORMAL}-h${COLOR_RESET}  help

${WHITE_BOLD}Hotkeys${COLOR_RESET}
  ${GREEN_NORMAL}?     ${COLOR_RESET}  help
  ${GREEN_NORMAL}ctrl-b${COLOR_RESET}  open the file in the browser
  ${GREEN_NORMAL}ctrl-e${COLOR_RESET}  open the file content in the editor
  ${GREEN_NORMAL}ctrl-o${COLOR_RESET}  open the search query in the browser
  ${GREEN_NORMAL}ctrl-p${COLOR_RESET}  quit and copy the last query to the clipboard using 'pbcopy' macOS
  ${GREEN_NORMAL}ctrl-r${COLOR_RESET}  reload
  ${GREEN_NORMAL}enter ${COLOR_RESET}  open the file in the pager
  ${GREEN_NORMAL}tab   ${COLOR_RESET}  toggle the file preview
  ${GREEN_NORMAL}esc   ${COLOR_RESET}  quit

${WHITE_BOLD}Search query examples${COLOR_RESET}
  ${DARK_GRAY}# searches only in the 'junegunn/fzf' repo for 'FZF_PORT'${COLOR_RESET}
  gh find-code 'repo:junegunn/fzf FZF_PORT'
  ${DARK_GRAY}# find '.rs' files with the string 'Hello, world!'${COLOR_RESET}
  gh find-code 'extension:rs "Hello, world!"'

${DARK_GRAY}# The syntax for searching code is described in the link below.${COLOR_RESET}
${DARK_GRAY}# https://docs.github.com/en/search-github/searching-on-github/searching-code ${COLOR_RESET}
EOF
	)
	echo -e "$help_text"
}

# ====================== parse command-line options =======================

while getopts "dhl:" opt; do
	case ${opt} in
		d)
			fzf_prompt="$(printf "%b❮ 𝙳𝚎𝚋𝚞𝚐 𝙼𝚘𝚍𝚎 ❯ Code: %b" "$YELLOW_NORMAL" "$COLOR_RESET")"
			export GH_DEBUG="api"
			debug_mode="true"
			;;
		l)
			if ((OPTARG < 1 || OPTARG > 100)); then
				die "Value for '-l' must be between 1 and 100"
			fi
			gh_user_limit="${OPTARG}"
			;;
		h)
			print_help_text
			exit 0
			;;
		*) die "Invalid Option: -$OPTARG" ;;
	esac
done
shift "$((OPTIND - 1))"

# ====================== check requirements =======================

for tool in bat column curl fzf gh python; do
	if ! type -p $tool >/dev/null; then
		die "'$tool' was not found."
	fi
done

check_version fzf "$min_fzf_version"
check_version gh "$min_gh_version"

# Verify if there are at least two spaces between columns. The delimiter in 'fzf' is set to
# '\t' or '\s\s+' to separate fields. By default, the 'column' command should separate any
# columns with two spaces. If this is not the case, you cannot proceed. It appears that
# older versions, e.g. BSD 1997, of 'column' had a default of two spaces.
# https://github.com/freebsd/freebsd-src/blob/0da30e9aa/usr.bin/column/column.c#L245
# Newer versions allow the output-separator to be defined.
# https://github.com/util-linux/util-linux/commit/47bd8ddc
# https://github.com/util-linux/util-linux/issues/1699#issuecomment-1140972918
# https://man7.org/linux/man-pages/man1/column.1.html

if [[ $(column -t <<<"A Z" 2>/dev/null) != *"  "* ]]; then
	die "Your 'column' command does not separate columns with at least two spaces. Please report this issue, stating your operating system and 'column' version."
fi

# ===================== helper functions ==========================

# send a POST request to fzf
curl_custom() {
	command curl --header "x-api-key: $FZF_API_KEY" \
		--request POST "localhost:$(cat "$store_fzf_port")" \
		--silent --data "${@:?"Missing 'data' input!"}"
}

sanitize_input() {
	if [[ -n ${2-} ]]; then
		# replace spaces with '+' and special characters with percent-encoded values
		python -c "import urllib.parse; print(urllib.parse.quote_plus('''$1'''))"
	else
		# replaces spaces with '%20' and special characters with percent-encoded values
		python -c "import urllib.parse; print(urllib.parse.quote('''$1'''))"
	fi
}

play_notification_sound() {
	# natively installed audio player for macOS, or fall back to the ASCII bell character
	afplay /System/Library/Sounds/Basso.aiff 2>/dev/null || echo -e "\a"
}

open_query_in_browser() {
	local sanitized_query
	sanitized_query=$(sanitize_input "$1" true)
	if [ -n "$sanitized_query" ]; then
		python -m webbrowser "https://github.com/search?q=${sanitized_query}&type=code"
	else
		play_notification_sound
	fi
}

last_action() {
	#  copies the last query to the clipboard
	if command -v pbcopy >/dev/null && [ -n "$1" ]; then
		printf "%q" "$1" | pbcopy
	fi
}

gh_query() {
	local data input="$*"
	local items total_count skip_count
	local index owner_repo_name file_name file_path patterns
	local file_extension sanitized_patterns sanitized_owner_repo_name sanitized_file_path
	local matched_line error_encountered redirect_location index_color
	declare -a line_numbers
	if data=$(gh api search/code \
		--method GET \
		--cache "$gh_default_cache_time" \
		--header "$gh_accept_json" \
		--header "$gh_accept_text_match" \
		--header "$gh_rest_api_version" \
		--field "per_page=$gh_user_limit" \
		--raw-field q="${input}" \
		--jq \
		$'"\(.items|length) \(.total_count)",
		(.items | to_entries[] | {
			owner_repo_name: .value.repository.full_name,
			file_name: .value.name,
			file_path: .value.path,
			index: (.key + 1),
			# create a unique list of patterns separated by a vertical line to use in
			# extended grep
			patterns: ([.value.text_matches[] | .. | .text? | select(type=="string")] as $patterns_array |
				if $patterns_array == [] then "__NoPatternFound__" else $patterns_array | unique | join("|") end)
		} | [.index, .owner_repo_name, .file_name, .file_path, .patterns] | @tsv)' 2>"$store_gh_search_debug"); then
		{
			error_encountered=false
			skip_count=0
			redirect_location="/dev/null"
			# Ensure the file is empty before initiating the loop, as it appends the
			# input list to the file throughout the loop.
			: >"$store_tee_append"
			: >"$store_skip_count"
			# first line
			IFS=' ' read -r items total_count

			# listed items
			while IFS=$'\t' read -r index owner_repo_name file_name file_path patterns; do
				# https://github.com/junegunn/fzf/issues/398
				# TODO: Improve the solution for terminating this while loop, when the script is exited.
				# Tested with 'sudo opensnoop -n bash', without a break check it
				# keeps going through the data list.
				# Check if the parent process is still running or kill the loop
				! kill -0 "$PPID" 2>/dev/null && break
				index_color="$WHITE_NORMAL"
				file_extension="null"
				# Check if the file has a file extension and assign it.
				if [[ $file_name =~ \.[[:alnum:]]+$ ]]; then
					file_extension="${file_name##*.}"
				fi
				# This covers special cases where syntax highlighting requires a leading
				# dot, such as filenames like 'zshrc', '.zshrc' or 'macos.zshrc'
				if bat --list-languages --color=never | grep --quiet --word-regexp "\.${file_extension}"; then
					file_extension=".${file_extension}"
				elif bat --list-languages --color=never | grep --quiet --word-regexp "\.${file_name}"; then
					file_extension=".${file_name}"
				fi

				# These sanitizations are necessary because file paths may contain special
				# characters, such as hashtags (#).
				sanitized_owner_repo_name=$(sanitize_input "$owner_repo_name")
				sanitized_file_path=$(sanitize_input "$file_path")
				cp "$store_file_contents" "${store_file_contents}_${index}"
				cp "$store_file_contents" "${store_file_contents}_${index}_line_numbers"

				# Escape special charters before using the string in extended 'grep'.
				# However, the "|" character should be left unescaped.
				# shellcheck disable=SC2001
				sanitized_patterns=$(sed -e 's/[][?*+.\/$^(){}]/\\&/g' <<<"$patterns")

				if gh api "repos/${sanitized_owner_repo_name}/contents/${sanitized_file_path}" \
					--cache "$gh_default_cache_time" \
					--header "$gh_accept_raw" \
					--header "$gh_rest_api_version" \
					>"${store_file_contents}_${index}" \
					2>"$store_gh_content_debug"; then
					# The first attempt is the typical way and is usually successful.
					:
				elif gh api "https://raw.githubusercontent.com/${sanitized_owner_repo_name}/HEAD/${sanitized_file_path}" \
					--cache "$gh_default_cache_time" \
					--header "$gh_accept_raw" \
					--header "$gh_rest_api_version" \
					>"${store_file_contents}_${index}" \
					2>"$store_gh_content_debug"; then
					# This case covers 'symlinked' files, for example:
					# 'repo:model-checking/kani in:path macos'.
					:
				else
					# There could be several reasons why pulling content might fail. One
					# reason could be outdated cached search results from GitHub. For
					# example, a user might have deleted their account, but their content
					# is still in the search index.
					echo "$index" >>"$store_skip_count"
					if $debug_mode; then
						error_encountered=true
					else
						{
							cat "$store_gh_content_debug"
							printf "\n[%s] SKIPPED: The contents of this file couldn't be fetched.\n\n" "$(date -u +%Y-%m-%dT%H-%M-%S)"
						} >>"${store_file_contents}_${index}"
					fi
					index_color="$RED_NORMAL"
					patterns="__NoPatternFound__"
				fi

				curl_custom "transform-header:printf '%b%s of %s collected...%b' '$DARK_GRAY' \
					'$index' '$((total_count > gh_user_limit ? gh_user_limit : total_count))' '$COLOR_RESET'"

				if $debug_mode; then
					redirect_location="${store_grep_extended_debug}_${index}"
				fi

				line_numbers=()
				[[ $patterns != "__NoPatternFound__" ]] && while IFS='' read -r matched_line; do
					line_numbers+=("$matched_line")
					# '--' is used as an indicator to signify the end of command options.
					# After this, 'sanitized_patterns' is treated as an argument, not as
					# an option, as it may start with a dash '-'.
				done < <(grep --extended-regexp --line-number -- \
					"$sanitized_patterns" "${store_file_contents}_${index}" 2>"${redirect_location}" | cut -d: -f1)
				# Save additional information only if an error is encountered by grep
				if $debug_mode && [[ -s ${store_grep_extended_debug}_${index} ]]; then
					{
						for value in "index" "owner_repo_name" "file_path" "patterns" "sanitized_patterns"; do
							echo "$value = '${!value}'"
						done
					} >>"${store_grep_extended_debug}_${index}" 2>&1
				fi

				echo "${line_numbers[*]}" >"${store_file_contents}_${index}_line_numbers"
				printf "%s\t%s\t%b%-3d%b\t%b%s%b/%b%s%b\t%b%s/%b%s%b\n" \
					"${line_numbers:-1}" "$file_extension" "$index_color" "$index" "$COLOR_RESET" \
					"$CYAN_NORMAL" "${owner_repo_name%/*}" "$COLOR_RESET" "$CYAN_BOLD" \
					"${owner_repo_name#*/}" "$COLOR_RESET" "$MAGENTA_NORMAL" "$(dirname "$file_path")" \
					"$MAGENTA_BOLD" "$(basename "$file_path")" "$COLOR_RESET" |
					tee -a "$store_tee_append"

				if $error_encountered; then
					break
				fi
			done
			# Format the input list into a structured table.
			column -ts $'\t' <"$store_tee_append" >"$store_input_list"
			skip_count="$(sed -n '$=' "$store_skip_count")"

			if $error_encountered; then
				{
					echo
					gh api rate_limit \
						--header "$gh_accept_json" \
						--header "$gh_rest_api_version" \
						--jq \
						'(["List API Limits", "Used/Limit", "Resetting"] | (., map(length*"¯"))),
						(.resources | to_entries[] | {
							name: .key,
							used_limit: "\(.value.used)/\(.value.limit)",
							reset: "\(.value.reset | strflocaltime("%H:%M:%S %Z") ) (\((.value.reset - now) | (./60|ceil))m)"
						}  | [.name, .used_limit, .reset]) | @tsv' |
						column -ts $'\t' |
						bat --plain --language COMMIT_EDITMSG
				} >>"$store_gh_content_debug"
				curl_custom "transform-header(printf '%bAPI failed for repos/%s/contents/%s%b' \
					'$RED_NORMAL' '$owner_repo_name' '$file_path' '$COLOR_RESET')+change-preview:cat '$store_gh_content_debug'"
			elif ((skip_count > 0)); then
				curl_custom "reload(cat $store_input_list)+transform-header:printf '%b%s of ∑ %s%b (Skipped: %d %s [%s])%b | ? help · esc quit%b\n' \
					'$YELLOW_NORMAL' '$items' '$total_count' '$RED_NORMAL' '$skip_count' \
					'$([[ $skip_count -gt 1 ]] && echo items || echo item)' \
					'$(paste -sd "," "$store_skip_count")' '$DARK_GRAY' '$COLOR_RESET'"
			else
				curl_custom "reload(cat $store_input_list)+transform-header:printf '%b%s of ∑ %s%b | ? help · esc quit%b\n' \
					'$YELLOW_NORMAL' '$items' '$total_count' '$DARK_GRAY' '$COLOR_RESET'"
			fi

		} <<<"$data"

	else
		if [ -z "$input" ]; then
			curl_custom "transform-header:printf '%bPlease enter a search query.%b' '$DARK_GRAY' '$COLOR_RESET'"
		else
			curl_custom "transform-header:printf '%bFailed to get the search results, check the query syntax.%b' \
				'$RED_NORMAL' '$COLOR_RESET'"
		fi
	fi
}

view_contents() {
	declare -a line_numbers bat_args editor_args less_args
	local file_extension index file_path
	local file_name tempfile_with_ext less_move_to_line
	IFS=$'\t' read -r _ file_extension index _ file_path < <(sed -E $'s/[[:space:]]{2,}/\t/g' <<<"$@")
	# Remove trailing whitespace that was caused by the '%-3d' placeholder in 'printf'.
	index=$(tr -d '[:space:]' <<<"$index")

	# The '--wrap never' option is necessary as, without it, the 'fzf' preview may
	# occasionally navigate to the incorrect line. The '--theme' option is not required
	# due to the 'BAT_THEME' set at the beginning.
	bat_args=(
		"--wrap=never"
		"--style=numbers,header-filename,grid"
		"--color=always"
	)

	[[ $file_extension != "null" ]] && if bat --language "$file_extension" <<<"test" >/dev/null 2>&1; then
		bat_args+=("--language=${file_extension}")
	fi
	IFS=' ' read -ra line_numbers <"${store_file_contents}_${index}_line_numbers"

	# NOTE: The '--line-range' in 'bat' overrides preceding flags. However, the
	# '--highlight-line' attribute can be  utilized multiple times.
	# https://github.com/sharkdp/bat/pull/162#pullrequestreview-125072252
	for number in "${line_numbers[@]}"; do
		bat_args+=("--highlight-line=${number}")
	done
	file_name=$(basename "$file_path")

	# Replace single quotes with escaped back ticks. A file_name might start with a dash
	# (-). Ensure there is no space between '--file-name' and the argument.
	bat_args+=("--file-name='${file_name//"'"/\`} │ 🅻  ${line_numbers[*]:-<none>}'")

	if $open_in_editor; then
		tempfile_with_ext="${store_file_contents}_${index}_${file_name}"
		cp "${store_file_contents}_${index}" "$tempfile_with_ext"
		case $(basename "${EDITOR-}") in
			code | codium)
				editor_args=(--reuse-window --goto "${tempfile_with_ext}:${line_numbers:-1}")
				;;
			nano | nvim | vi | vim)
				editor_args=("+${line_numbers:-1}" "$tempfile_with_ext")
				;;
			*)
				play_notification_sound
				return 0
				;;
		esac
		$EDITOR "${editor_args[@]}"
		return 0
	fi

	if $debug_mode; then
		{
			echo -n "bat version: "
			bat --version
			echo -n "config file: "
			bat --config-file
			cat "$(bat --config-file)"
			for value in BAT_PAGER BAT_CONFIG_PATH BAT_STYLE BAT_THEME BAT_TABS PAGER; do
				echo "$value = '${!value}'"
			done
		} >"$store_bat_debug" 2>&1
	fi

	if $open_in_pager; then
		bat_args+=("--paging=always")
		# The 'less' pager can move to a specific line.
		if [[ $(basename "${PAGER-}") =~ ^(bat|less)$ ]]; then
			# If the user has assigned the environment variable LESS with the
			# '-F/--quit-if-one-screen' option, and explicitly set the '--pager' to 'less',
			# the screen will not remain open for small text files that fit on the entire
			# screen. The simplest solution is to unset the  'LESS' variable and define
			# custom settings. Replace "${LESS-}" with an empty string when 'LESS' is
			# already unset to avoid an error from 'set -o nounset'.
			[[ -n ${LESS-} ]] && unset LESS
			# Account for an offset of 3 lines for the bat header.
			less_move_to_line=$((${line_numbers:-1} + 3))
			less_args=(
				"--LONG-PROMPT"         # Long prompts ("Line X of Y")
				"--hilite-search"       # Highlight results when searching with slash key (/)
				"--jump-target=.3"      # percent on the screen for the target line
				"--quiet"               # be more quiet
				"--quit-on-intr"        # quit less immediately with ^C
				"--RAW-CONTROL-CHARS"   # colors will not work without it
				"--tilde"               # don't show '~' symbols on lines after EOF
				"+${less_move_to_line}" # as the variable name suggests
			)
			if [[ -z $(check_version less 550 echo) ]]; then
				# https://www.greenwoodsoftware.com/less/old.html
				# mouse input came with version 550
				less_args+=("--mouse")
			fi
			# https://github.com/sharkdp/bat#using-a-different-pager
			bat_args+=("--pager='less ${less_args[*]}'")
		fi
	else
		# Not needed in the pager, as these environment variables aren't expanded there.
		bat_args+=("--terminal-width=${FZF_PREVIEW_COLUMNS:-$COLUMNS}")
	fi
	eval bat "${bat_args[*]}" "${store_file_contents}_${index}"
}

# ===================== lets begin ========================

: | fzf \
	--ansi \
	--bind $'start:execute-silent(echo $FZF_PORT > $store_fzf_port)+reload:gh_query {q}' \
	--bind "change:first+reload:sleep 0.65; gh_query {q} || true" \
	--bind 'ctrl-b:execute-silent:gh browse --repo {4} {5}:{1}' \
	--bind 'ctrl-e:execute:[[ -n {q} && -n {} ]] && open_in_editor=true view_contents {}' \
	--bind 'ctrl-o:execute-silent:open_query_in_browser {q}' \
	--bind 'ctrl-p:become:last_action {q}' \
	--bind 'ctrl-r:reload:gh_query {q} || true' \
	--bind 'enter:execute:[[ -n {q} && -n {} ]] && open_in_pager=true view_contents {}' \
	--bind 'esc:become:' \
	--bind '?:toggle-preview+change-preview(print_help_text)+change-preview-window:~0:+1' \
	--bind 'load:change-preview([[ -n {q} && -n {} ]] && view_contents {})+change-preview-window:+{1}+3/3' \
	--bind 'scroll-up:offset-up,scroll-down:offset-down' \
	--bind 'tab:toggle-preview+change-preview-window(hidden|nohidden:+{1}+3/3)+change-preview:[[ -n {q} && -n {} ]] && view_contents {}' \
	--border block \
	--color 'bg+:233,bg:235,gutter:235,border:238,scrollbar:235' \
	--color 'preview-bg:234,preview-border:236,preview-scrollbar:237' \
	--color 'fg+:255,fg:regular:250,hl:40,hl+:40' \
	--color 'pointer:9,spinner:92,marker:46' \
	--color 'prompt:14,info:40,header:255:regular,label:bold' \
	--delimiter '\t|\s\s+' \
	--disabled \
	--ellipsis '' \
	--height=100% \
	--header-lines 0 \
	--info hidden \
	--layout reverse \
	--listen \
	--no-multi \
	--pointer '▶' \
	--preview "[[ -n {q} && -n {} ]] && view_contents {}" \
	--preview-window 'border-block:~3:+{1}+3/3:nohidden:right:nowrap:65%:<70(bottom:75%)' \
	--prompt "$fzf_prompt" \
	--query "$*" \
	--scroll-off 3 \
	--scrollbar '│▐' \
	--separator '' \
	--unicode \
	--with-nth=3..
