---
name: Quality check
on:
  push:
  pull_request_target:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@master
      - uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: --external-sources --norc
          SHFMT_OPTS: --simplify --indent 2 --case-indent
        with:
          sh_checker_comment: true
